(function(p){p(window,"undefined"===typeof window._acic?{}:window._acic,"undefined"===typeof window._aci_debug?!1:window._aci_debug)})(function(p,m,s){function l(){if(!(this instanceof l))return new l;this.version="0.0.14";this.urlHit="//www2.acint.net/hit/";this.urlJump="//www2.acint.net/jump/";this.urlPing="//www2.acint.net/ping/";this.cookieName="aid";this.cookieValueOptOut="opt-out";this.uid="";this.presence={startTimeout:1E4,maxNofRequests:2,timeoutMultiplier:2,nofRequests:0};this.config={dataProvider:"",
allowExtLinksTrack:!0,allowPresenceTrack:!0,customData:null}}var t=!!s,r={};"object"==typeof JSON&&"function"==typeof JSON.stringify?r.stringify=function(a){return JSON.stringify(a)}:function(){function a(a){function b(a){return 10>a?"0"+a:a}if(a&&"object"==typeof a){if(a instanceof Date)return isFinite(a.valueOf())?a.getUTCFullYear()+"-"+b(a.getUTCMonth()+1)+"-"+b(a.getUTCDate())+"T"+b(a.getUTCHours())+":"+b(a.getUTCMinutes())+":"+b(a.getUTCSeconds())+"Z":null;if(a instanceof String||a instanceof
Number||a instanceof Boolean)return a.valueOf()}return a}function c(a){f.lastIndex=0;return f.test(a)?'"'+a.replace(f,function(a){var b=e[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function b(f,e){var k,l,m,p,r=d,q,n=e[f],n=a(n);"function"===typeof h&&(n=h.call(e,f,n));switch(typeof n){case "string":return c(n);case "number":return isFinite(n)?String(n):"null";case "boolean":case "null":return String(n);case "object":if(!n)return"null";d+=
g;q=[];if("[object Array]"===Object.prototype.toString.apply(n)){p=n.length;for(k=0;k<p;k+=1)q[k]=b(k,n)||"null";m=0===q.length?"[]":d?"[\n"+d+q.join(",\n"+d)+"\n"+r+"]":"["+q.join(",")+"]";d=r;return m}if(h&&"object"===typeof h)for(p=h.length,k=0;k<p;k+=1)l=h[k],"string"===typeof l&&(m=b(l,n))&&q.push(c(l)+(d?": ":":")+m);else for(l in n)Object.prototype.hasOwnProperty.call(n,l)&&(m=b(l,n))&&q.push(c(l)+(d?": ":":")+m);m=0===q.length?"{}":d?"{\n"+d+q.join(",\n"+d)+"\n"+r+"}":"{"+q.join(",")+"}";
d=r;return m}}var f,d,g,e,h;"function"!==typeof r.stringify&&(f=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,e={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},r.stringify=function(a,c,f){var e;g=d="";if("number"===typeof f)for(e=0;e<f;e+=1)g+=" ";else"string"===typeof f&&(g=f);if((h=c)&&"function"!==typeof c&&("object"!==typeof c||"number"!==typeof c.length))throw Error("JSONStub.stringify");
return b("",{"":a})})}();var e={generateUUID:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var c=16*Math.random()|0;return("x"==a?c:c&3|8).toString(16)}).toLowerCase()},stringTrimLimit:function(a){if(null==a)return"";a=a.replace(/\s+/gmi," ").replace(/^\s+|\s+$/g,"");1E3<a.length&&(a=a.substr(0,1E3));return a},padInt:function(a){return 10>a?"0"+a:""+a},getTimeZoneOffsetIso8601:function(){var a=(new Date).getTimezoneOffset();return(0<a?"-":"+")+this.padInt(Math.floor(Math.abs(a)/
60))+":"+this.padInt(Math.abs(a)%60)},getDateTimeIso8601:function(a){var c=new Date;return c.getFullYear()+"-"+this.padInt(c.getMonth()+1)+"-"+this.padInt(c.getDate())+"T"+this.padInt(c.getHours())+":"+this.padInt(c.getMinutes())+":"+this.padInt(c.getSeconds())+"."+String((c.getMilliseconds()/1E3).toFixed(3)).slice(2,5)+(!0===a?this.getTimeZoneOffsetIso8601:"")},isObject:function(a){return"object"===typeof a&&"[object Object]"===Object.prototype.toString.call(a)},isArray:function(a){return"undefined"!==
typeof Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)},isEmptyObject:function(a){for(var c in a)return!1;return!0},isString:function(a){return"string"===typeof a||a instanceof String},encodeUriParam:function(a){if(null==a)return"";a=""+a;return encodeURIComponent instanceof Function?encodeURIComponent(a):escape(a)},implodeUriParams:function(a){var c,b=[];for(c in a)a.hasOwnProperty(c)&&b.push(c+"="+a[c]);return b.join("&")},makeRequestUri:function(a,c){return a+
"?"+e.implodeUriParams(c)},makeRequestImage:function(a){(window.Image?new Image:document.createElement("img")).src=a},addReadOnlyProperty:function(a,c,b){Object.defineProperty(a,c,{value:b,writeable:!1,enumerable:!0,configurable:!1})},addEventListenerCrossBrowser:function(a,c,b){if(a.addEventListener)a.addEventListener(c,b,!1);else if(a.attachEvent)a.attachEvent("on"+c,b);else throw"Cannot add event listener: no Event API support in client";},removeEventListenerCrossBrowser:function(a,c,b){if(a.removeEventListener)a.removeEventListener(c,
b,!1);else if(a.attachEvent)a.detachEvent("on"+c,b);else throw"Cannot remove event listener: no Event API support in client";},fireEventCrossBrowser:function(a,c){var b,f=document;if(f.createEvent){var d=null;switch(c){case "click":case "dblclick":case "mousedown":case "mouseup":case "mouseover":case "mousemove":case "mouseout":case "mouseenter":case "mouseleave":d="MouseEvent";break;case "wheel":d="WheelEvent";break;case "load":case "unload":case "abort":case "error":case "select":case "resize":case "scroll":d=
"UIEvent";break;case "focus":case "focusin":case "focusout":case "blur":d="FocusEvent";break;case "beforeinput":case "input":d="InputEvent";break;case "keydown":case "keyup":d="KeyboardEvent";break;case "compositionstart":case "compositionupdate":case "compositionend":d="CompositionEvent"}try{b=f.createEvent(d)}catch(e){try{b=f.createEvent("HtmlEvents")}catch(k){try{b=f.createEvent("Event")}catch(h){throw Error("Cannot create event object for specified event: "+c);}}}b.initEvent(c,!0,!1);a.dispatchEvent(b)}else if(f.createEventObject)b=
f.createEventObject(),b.eventType=c,a.fireEvent("on"+c,b);else if("function"==typeof a["on"+c])a["on"+c]()},fireSameEventCrosBrowser:function(a,c,b){var f=document,d;if(f.createEvent)try{d=new b.constructor(c,b),a.dispatchEvent(d)}catch(e){d=f.createEvent("MouseEvent"),d.initMouseEvent(b.type,!0,!0,window,0,b.screenX,b.screenY,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget||null),a.dispatchEvent(d)}else if(f.createEventObject)d=f.createEventObject(b),d.eventType=
c,a.fireEvent("on"+c,d);else if("function"==typeof a["on"+c])a["on"+c]()},bindOnReady:function(a){function c(){f||(f=!0,a())}function b(){if(!f)try{k.doScroll("left"),c()}catch(a){setTimeout(b,10)}}var f=!1,d=window,e=document,k=e.documentElement;if(e.addEventListener)e.addEventListener("DOMContentLoaded",c,!1);else if(e.attachEvent){try{var h=null!=d.frameElement}catch(l){}k.doScroll&&!h&&b();e.attachEvent("onreadystatechange",function(){"complete"===e.readyState&&c()})}else if(d.addEventListener)d.addEventListener("load",
c,!1);else if(d.attachEvent)d.attachEvent("onload",c);else{var m=d.onload;d.onload=function(){m&&m();c()}}},cookies:{getItem:function(a){return decodeURIComponent(document.cookie.replace(RegExp("(?:(?:^|.*;)\\s*"+encodeURIComponent(a).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*([^;]*).*$)|^.*$"),"$1"))||null},setItem:function(a,c,b,f,d,e){if(!a||/^(?:expires|max\-age|path|domain|secure)$/i.test(a))return!1;var k="";if(b)switch(b.constructor){case Number:k=Infinity===b?"; expires=Fri, 31 Dec 9999 23:59:59 GMT":
"; max-age="+b;break;case String:k="; expires="+b;break;case Date:k="; expires="+b.toUTCString()}document.cookie=encodeURIComponent(a)+"="+encodeURIComponent(c)+k+(d?"; domain="+d:"")+(f?"; path="+f:"")+(e?"; secure":"");return!0},removeItem:function(a,c,b){if(!a||!this.hasItem(a))return!1;document.cookie=encodeURIComponent(a)+"=; expires=Thu, 01 Jan 1970 00:00:00 GMT"+(b?"; domain="+b:"")+(c?"; path="+c:"");return!0},hasItem:function(a){return RegExp("(?:^|;\\s*)"+encodeURIComponent(a).replace(/[\-\.\+\*]/g,
"\\$&")+"\\s*\\=").test(document.cookie)},keys:function(){for(var a=document.cookie.replace(/((?:^|\s*;)[^\=]+)(?=;|$)|^\s*|\s*(?:\=[^;]*)?(?:\1|$)/g,"").split(/\s*(?:\=[^;]*)?;\s*/),c=0;c<a.length;c++)a[c]=decodeURIComponent(a[c]);return a}}};l.prototype.init=function(){this.isAlreadyLoaded()||e.cookies.hasItem(this.cookieName)&&this.cookieValueOptOut==e.cookies.getItem(this.cookieName)||(this.uid=e.generateUUID(),this.parseConfig(),this.initHit(),!0===this.config.allowExtLinksTrack&&this.initExtLinksTrack(),
!0===this.config.allowPresenceTrack&&this.initPresenceTrack())};l.prototype.initHit=function(){var a=e.makeRequestUri(this.urlHit,this.collectDataOnInit());e.makeRequestImage(a)};l.prototype.initExtLinksTrack=function(){var a=this,c=document,b=function(b){var c=window,g=!1,k;b=b||c.event;var h=b.target||b.srcElement,l=h;if(!("tagName"in h&&"a"==h.tagName.toLowerCase())){for(g=h.parentNode;g;){if("tagName"in g&&"a"==g.tagName.toLowerCase()){k=g;break}if("parentNode"in g)g=g.parentNode;else break}if(k)h=
k;else return}if("href"in h&&/^(http:|https:|)\/\/.+/.test(h.href)&&!("hostname"in h&&h.hostname===c.location.hostname)){if(b.shiftKey||b.altKey||b.ctrlKey||b.metaKey)g=!0;g=!0;h.hasOwnProperty("_delayClick")?!1===h.hasOwnProperty("_canSkipDelay")?"preventDefault"in b?b.preventDefault():b.returnValue=!1:(delete h._canSkipDelay,delete h._delayClick):(c=e.makeRequestUri(a.urlJump,a.collectDataOnClick(b,h)),e.makeRequestImage(c),!1===g&&(h._delayClick=!0,setTimeout(function(){h._canSkipDelay=!0;e.fireSameEventCrosBrowser(l,
"click",b)},200),"preventDefault"in b?b.preventDefault():b.returnValue=!1))}};"interactive"==c.readyState||"complete"==c.readyState?e.addEventListenerCrossBrowser(c.body,"click",b):e.bindOnReady(function(){e.addEventListenerCrossBrowser(c.body,"click",b)})};l.prototype.initPresenceTrack=function(){var a=this,c=function(){var b=e.makeRequestUri(a.urlPing,a.collectDataOnPresencePing());e.makeRequestImage(b);a.presence.nofRequests+=1;a.presence.nofRequests<a.presence.maxNofRequests&&(b=a.presence.startTimeout*
Math.pow(a.presence.timeoutMultiplier,a.presence.nofRequests),setTimeout(c,b))};setTimeout(c,this.presence.startTimeout)};l.prototype.isAlreadyLoaded=function(){if("object"==typeof p._acil&&"function"==typeof p._acil.isLoaded)return!0;"undefined"!==typeof Object.defineProperty?(e.addReadOnlyProperty(p,"_acil",{}),e.addReadOnlyProperty(p._acil,"isLoaded",function(){return!0})):p._acil=function(){return{isLoaded:function(){return!0}}}();return!1};l.prototype.parseConfig=function(){if(e.isObject(m)&&
!e.isEmptyObject(m)){var a=["dataProvider"],c=["allowExtLinksTrack","allowPresenceTrack"],b=["customData"],f,d;for(d=0;d<a.length;d++)f=a[d],m.hasOwnProperty(f)&&(this.config[f]=isNaN(parseInt(m[f],10))?this.config[f]:Math.abs(parseInt(m[f],10)));for(d=0;d<c.length;d++)f=c[d],m.hasOwnProperty(f)&&(this.config[f]=!0===m[f]);for(d=0;d<b.length;d++)if(f=b[d],m.hasOwnProperty(f)&&(a=m[f],!("undefined"===typeof a||null==a||"function"==typeof a||e.isString(a)&&0===a.length||e.isObject(a)&&e.isEmptyObject(a)||
e.isArray(a)&&0===a.length))){try{if(e.isObject(a)||e.isArray(a)){if(a=r.stringify(a),"{}"===a||"[]"===a)a=null}else e.isString(a)||(a=a.toString(),0===a.length&&(a=null))}catch(g){if(a=null,!0===s)throw g;}this.config[f]=a}}};l.prototype.dataAddObligatoryParams=function(a){a.v=this.version;a.uid=this.uid;a.dp=this.config.dataProvider;a.tz=e.encodeUriParam(e.getTimeZoneOffsetIso8601());a.nc=Math.random().toString().substr(2,8)};l.prototype.collectDataOnInit=function(){var a=document,c=window,b={u:e.encodeUriParam(c.location.href),
r:e.encodeUriParam(a.referrer||""),rs:c.screen.width+"x"+c.screen.height,t:e.encodeUriParam(e.stringTrimLimit(a.title)),oE:+this.config.allowExtLinksTrack,oP:+this.config.allowPresenceTrack,dT:e.encodeUriParam(e.getDateTimeIso8601(!1))};null!==this.config.customData&&(b.cd=e.encodeUriParam(e.stringTrimLimit(this.config.customData)));c.parent!==c&&(b["if"]=e.encodeUriParam(c.location.href),b.u=e.encodeUriParam(a.referrer||""),b.r="");this.dataAddObligatoryParams(b);return b};l.prototype.collectDataOnClick=
function(a,c){var b=document,f=window,d={vP:"",c:"",r:"",u:"",aT:"",hT:0},g=a.target.ownerDocument||b,b=g.documentElement,g=g.body;d.vP=(f.innerWidth||b.clientWidth||g.clientWidth)+"x"+(f.innerHeight||b.clientHeight||g.clientHeight);null==a.pageX&&null!=a.clientX?d.c=a.clientX+(b&&b.scrollLeft||g&&g.scrollLeft||0)-(b&&b.clientLeft||g&&g.clientLeft||0)+"x"+(a.clientY+(b&&b.scrollTop||g&&g.scrollTop||0)-(b&&b.clientTop||g&&g.clientTop||0)):null!==a.pageX&&(d.c=a.pageX+"x"+a.pageY);d.r=e.encodeUriParam(f.location.href);
d.u=e.encodeUriParam(c.href);var f=c.childNodes,k=0,h=0,l=0;if(1<=f.length){for(b=0;b<f.length;b++)g=f[b],3!==g.nodeType&&1!==g.nodeType||1!==g.nodeType||(h+=1,"tagName"in f[b]&&"img"===f[b].tagName.toLowerCase()&&(k+=1,l=b));1==k&&k==h?d.hT=1:0<h&&(d.hT=2)}switch(d.hT){case 1:d.aT=f[l].getAttribute("alt")||"";break;case 2:case 0:d.aT=c.innerHTML?c.innerHTML.toString().replace(/<\/?[^>]+>/gmi,""):""}0<d.aT.length&&(d.aT=e.stringTrimLimit(d.aT),""!==d.aT&&(d.aT=/^(\S+(\s|)){1,10}/gmi.exec(d.aT)[0].replace(/^\s+|\s+$/g,
"")));d.aT=e.encodeUriParam(d.aT);this.dataAddObligatoryParams(d);return d};l.prototype.collectDataOnPresencePing=function(){var a={dT:e.encodeUriParam(e.getDateTimeIso8601(!1))};this.dataAddObligatoryParams(a);return a};try{(new l).init()}catch(u){if(!0===t)throw u;}});
